settings:
  bullet: "-"
  emphasis: "_"
  strong: "*"
  listItemIndent: one
plugins:
  - remark-frontmatter
  - remark-preset-lint-consistent
  - remark-preset-lint-recommended
  - - remark-lint-list-item-indent
    - "space"
  - - remark-lint-emphasis-marker
    - "_"
  - - remark-lint-strong-marker
    - "*"
